#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
#
echo "In the corner is a decaying old altar of some forgotten god."
printf "\n"
echo "There is a small trinket on the ground."
echo "It looks religious in nature."
echo "Do you want to put the trinket back on the altar?"
printf "\n"
read RESP

if [ $RESP = "y" -o $RESP = "Y" ]; then
   echo "You place the trinket upon the altar."
   echo "You feel a gentle breeze pass through the room."
   touch .bless
else
   echo "Do you want to take the trinket for yourself?"
   read RESP
   if [ $RESP = "y" -o $RESP = "Y" ]; then
       echo "Remember to add the trinket to your inventory!"
       touch .curse
   else
   echo "You leave the trinket where it lies."
   echo "There is a great sadness here."
   echo "You feel compelled to move on."
   touch .curse
   fi
fi


















































































































































































































































































# Hmm, that didn't work.
#
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./altar
#
# If you're not seeing the * after
# this file name, you're probably
# forgetting to use ls -F 


