#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
#
echo "You have found a potion bottle of swirling"
echo "green liquid. Do you want to drink it?"
printf "\n"
read RESP

if [ $RESP = "y" -o $RESP = "Y" ]; then
   echo "The taste of a rustic green plant fills your mouth."
   echo "It warms and strengthens you."
   printf "\n" 
   echo "Create a variable for your health points (HP)."
   echo "You have 15 HP:"
   echo "$ export HP=15"
   printf "\n"
else
   echo "You weren't born yestermorn;"
   echo "this potion is probably poison."
   printf "\n"   
   echo "Create a variable for your health points (HP)."
   echo "You have 10 HP:"
   echo "$ export HP=10"
   printf "\n"
fi

echo "You can check your health at any time:"
printf "\n"
echo "echo \$HP"
printf "\n"
mv ../../.chapel ../../chapel 2>/dev/null
mv ../../.vault ../../vault 2>/dev/null
mv ../../.scrap ../../scrap 2>/dev/null




















































































































































































































































































# Hmm, that didn't work.
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./potion

