#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
# 
printf "\n"
echo "You have found a gleaming silver **sword**!"
echo "You marvel at its craftmanship, and you recall"
echo "tales from your childhood of the great"
echo "mystic king Rannismir who bore such a sword to"
echo "protect the kingdom from undead."
printf "\n"
echo "Add this item to your inventory:"
printf "\n"
echo "$ export I=sword,\$I"
printf "\n"
echo "Remember, you can check your inventory:"
printf "\n"
echo "echo \$I"
printf "\n"
mv ../../.chapel ../../chapel 2>/dev/null
mv ../../.vault ../../vault 2>/dev/null
mv ../../.scrap ../../scrap 2>/dev/null

























































































































































































































































































# Hmm, that didn't work!
#
# Maybe the scroll can provide a clue.

