#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
# 
echo "Runes, the language of the ancient mystics that once ruled"
echo "this land, are inscribed upon the western wall."
echo "Do you want to read them?"
read RESP
if [ $RESP = "y" -o $RESP = "Y" ]; then
   echo "You recall the lessons of Caitlyn the Green,"
   echo "who taught you these ancient letters."
   printf "\n"
   echo "The runes are instructions on how to summon"
   echo "a portal that will allow you to walk through"
   echo "an invisible door contained in the wall."
   printf "\n"
   echo "In Bash, a symlink is an *alias* or a *shortcut*"
   echo "to another file or directory."
   echo "Create one from this room to the adjacent one:"
   echo "ln -f -s `pwd`/../../../chapel/courtyard/aviary/hall portal"
   printf "\n"
else
   echo "You decide it is probably best to leave"
   echo "magickal enscriptions as they are."
fi



























































































































































































































































































































# Hmm, that didn't work.
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./spell

