#!/bin/sh
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
# 
echo "A rugged statue stands in the corner of the room."
echo "Do you approach it?"
read RESP

if [ $RESP = "y" -o $RESP = "Y" ]; then
   echo "The statue springs to life, rumbling:"
   echo "WHO DARES INTRUDE UPON CHAMBER OF SPIRITS?"
   printf "\n" 
   echo "It thrusts a fist at you, hitting you for 5 damage."
   echo "Deduct 5 from your HP variable:"
   echo 'let "HP=HP-5"'
   sed -i 's/coins/diamonds/g' ./treasure
   printf "\n"
   echo "Do you have a sword?"
   read RESP
   if [ $RESP = "y" -o $RESP = "Y" ]; then
       echo "You slay the statue!"
   else
       echo "Run!"
       rm treasure
       rm spell
   fi
else
    echo "You cautiously avoid the statue,"
    echo "recalling stories of living stone"
    echo "lying in wait, deep within haunted catacombs."
   printf "\n"
fi













































































































































































































































































































# Hmm, that didn't work.
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./statue

