#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
# 
echo
if ! grep -Po coins <<< $I &> /dev/null; then
    echo "You have found a stash of **coins**!"
    echo "They are old and worn with age,"
    echo "but they still gleam in the magical light"
    echo "emanating from your eyes."
    printf "\n"
    echo "Prepend this item to your inventory:"
    printf "\n"
    echo '$ export I=coins,$I'
    printf "\n"
    echo "Remember, you can check your inventory:"
    printf "\n"
    echo 'echo $I'
    printf "\n"
else
    echo "This treasure has already been taken."
fi








































































































































































































































































































































# Hmm, that didn't work.
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./treasure

