#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
# 
echo "A metal box sits upon the ground."
echo "It appears to be illuminated from within."
echo "There is a window in the box."
echo "The window is black, but there is luminescent writing."

echo "Do you want to read the writing?"
read RESP

if [ $RESP = "y" -o $RESP = "Y" ]; then
   echo ".--------------------------------,"
   echo "|       Welcome to POSIX         |"
   echo "|   Enter your username:         |"
   echo "'--------------------------------'"
   read RESP
   if [ $RESP = $USER ]; then
       echo '#!/bin/bash
       echo "Welcome, $USER, to your POSIX system."
       echo "You have learnt much, and now you have"
       echo "the basic knowledge you need to become"
       echo "a truly powerful wizard."
       echo "You have found magickal armour."
       echo "Add it to your inventory."
       echo touch .armour' >> armour
       chmod +x armour
       touch .bless

       echo "You feel magic in the air."
   fi
else
   echo "The box is full of mystery, and it's often"
   echo "best not to look too deeply into puzzles."
fi


















































































































































































































































































# Hmm, that didn't work.
#
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./box
#
# If you're not seeing the * after
# this file name, you're probably
# forgetting to use ls -F 

