#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
# 
if [ -e drum ]; then
   echo "War drums pound in the distance,"
   echo "giving Nyarlathotep strength."
   printf "\n"
   echo "If you know a spell to un-summon the drums,"
   echo "Nyarlathotep would probably weaken!"
   echo "Look up the *mv* command."
else
   echo "The drumming has stopped."
   echo "Now's your chance to attack!"
fi


















































































































































































































































































# Hmm, that didn't work.
#
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./drummer
#
# If you're not seeing the * after
# this file name, you're probably
# forgetting to use ls -F 

