#!/bin/sh
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
# 
roll() {
    echo "Enter a number."
    read NUM
    ALPHA=$RANDOM
    OMEGA=$RANDOM
    A=`echo $ALPHA | cut -b 1-2`
    O=`echo $OMEGA | cut -b 1-2`
    let "NUM=$ALPHA % $OMEGA"
    MONSTER=$RANDOM
    MONSTER=`echo $MONSTER | cut -b 1-2`
    NUM=`echo $NUM | cut -b 1-2`

    let "MONSTER=MONSTER+3"
    
    if [ ! -e drum ]; then
       let "MONSTER=MONSTER-2"
    fi
    
    echo "The monster rolled " $MONSTER
    echo "You rolled " $NUM

    if [[ -e wizard-dark && -e wizard-light ]]; then
	let "NUM=NUM+2"
	echo "+2 Arnnisen the Gray"
    fi

if [[ -e ../../.bless ]]; then
	let "NUM=NUM+2"
	echo "+2 POSIX wizard bonus!"
    fi
    resolve
}

resolve() {
    if [[ $MONSTER -eq $NUM ]]; then
	echo "You dodge an attack, but you miss your mark as a result."
	echo "Roll again..."
	roll
    fi
    
    if [[ $MONSTER -lt $NUM ]]; then
       echo "A hit! A palpable hit!"
       echo "You have vanquished the elder god of chaos!"
       echo "\#\!/bin/sh" > treasure
       echo "echo 'You have found a lock of the **hair** of a god!'" > treasure
       echo "echo 'Add it to your inventory.'" >> treasure
       chmod +x treasure
       echo "\#\!/bin/sh" > platinum
       echo 'You have found an enchanted *bracelet* of chaotic necromancy!'" >> platinum
       echo " You have reached the end of the game." > end
       echo " You know enough Bash now to use it for every day activities." >> end
       echo " Practice makes perfect, so be sure to use it often. " >> end
       echo " For continued Bash tips, visit opensource.com often." >> end
       echo " And eventually, we hope to see you contribute " >> end
       echo " your own dungeon rooms to Bash crawl\!" >> end

       echo "echo 'Add it to your inventory.'" >> platinum
       chmod +x platinum
    else
	echo "Your sword swings harmlessly through the air."
	echo "You take 10 points damage from your foe. Deduct this from your HP."
	echo 'let "HP=HP-10"'
	printf "\n"
	roll
    fi
}

echo "In the blink of an eye, Nyarlathotep is standing before you."
echo "From its hands emanate black necrotic rays, and your mind screams."
printf "\n"
echo "Are you armed? y/n"
read RESP

if [ $RESP = "y" -o $RESP = "Y" ];then
    roll
    resolve
else
    echo "You turn to flee but find that you cannot."
    echo "You spend 1000 years as a mindless servant to the crawling chaos."
    echo "When you awaken, you may attempt to fight for your liberation."
    printf "\n"
fi
printf "\n"


















































































































































































































































































# Hmm, that didn't work.
#
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./nyarlathotep
#
# If you're not seeing the * after
# this file name, you're probably
# forgetting to use ls -F 

