#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
# 
if [ -e wizard-dark ]; then
   echo "The ancient wizard, Arnnisen the Gray,"
   echo "takes form before your very eyes. You"
   echo "have freed him, and now he fights by"
   echo "your side against the crawling chaos!"
else
   echo "You feel a presence."
   echo "It's probably just your imagination."
fi


















































































































































































































































































# Hmm, that didn't work.
#
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./wizard-light
#
# If you're not seeing the * after
# this file name, you're probably
# forgetting to use ls -F 

