#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
# 
echo "Do you have an ice crystal?"
printf "\n"
read RESP

no_crystal () {
   echo "You sense that the glass shards are searching for something."
   echo "Whatever it is, you cannot provide it now."
   echo "Walk with care."
}
if [ $RESP = "y" -o $RESP = "Y" ]; then
    if grep -Po crystal <<< $I &> /dev/null; then
        echo "You place the ice crystal among the shards of glass."
        echo "The sword in your hands becomes cold."
        echo "You feel the power of 1000 blizzards coursing through it."
        touch .bless
    else
        no_crystal
    fi
else
    no_crystal
fi


















































































































































































































































































# Hmm, that didn't work.

# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./glass


